version: "3.8"

networks:
  dev_env_network:
    driver: bridge

services:
  web:
    image: converttools:1.0.0
    container_name: web
    build: 
     context: .
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    ports:
      - "5000:5000"
    links:
      - redis
    depends_on:
      - redis
    env_file:
      - docker.env
    environment:
      - FLASK_ENV=production
    volumes:
      - .app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    hostname: redis

  worker:
    image: converttools:1.0.0
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A worker.celery worker --loglevel=info --pool=solo
    volumes:
      - ./app
    links:
      - redis
    env_file:
      - docker.env
    depends_on:
      - redis